/**
* mapwriter API generated from mapwriter.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* MapwriterBase.h
*
*
*/

#pragma once

#include "../serializer/MapwriterJsonObject.h"

#include "../Ports.h"

#include "polycube/services/cube.h"
#include "polycube/services/port.h"



#include "polycube/services/utils.h"
#include "polycube/services/fifo_map.hpp"

#include <spdlog/spdlog.h>

using namespace polycube::service::model;


class MapwriterBase: public virtual polycube::service::Cube<Ports> {
 public:
  MapwriterBase(const std::string name);
  
  virtual ~MapwriterBase();
  virtual void update(const MapwriterJsonObject &conf);
  virtual MapwriterJsonObject toJsonObject();

  /// <summary>
  /// Action performed on the received packet (i.e.,READ, WRITE headers: READ)
  /// </summary>
  virtual MapwriterActionEnum getAction() = 0;
  virtual void setAction(const MapwriterActionEnum &value) = 0;

  /// <summary>
  /// Entry of the ports table
  /// </summary>
  virtual std::shared_ptr<Ports> getPorts(const std::string &name);
  virtual std::vector<std::shared_ptr<Ports>> getPortsList();
  virtual void addPorts(const std::string &name, const PortsJsonObject &conf);
  virtual void addPortsList(const std::vector<PortsJsonObject> &conf);
  virtual void replacePorts(const std::string &name, const PortsJsonObject &conf);
  virtual void delPorts(const std::string &name);
  virtual void delPortsList();
};
