/**
* mapwriter API generated from mapwriter.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "MapwriterBase.h"

MapwriterBase::MapwriterBase(const std::string name) {
  logger()->set_pattern("[%Y-%m-%d %H:%M:%S.%e] [Mapwriter] [%n] [%l] %v");
}



MapwriterBase::~MapwriterBase() {}

void MapwriterBase::update(const MapwriterJsonObject &conf) {
  set_conf(conf.getBase());

  if (conf.actionIsSet()) {
    setAction(conf.getAction());
  }
  if (conf.portsIsSet()) {
    for (auto &i : conf.getPorts()) {
      auto name = i.getName();
      auto m = getPorts(name);
      m->update(i);
    }
  }
}

MapwriterJsonObject MapwriterBase::toJsonObject() {
  MapwriterJsonObject conf;
  conf.setBase(to_json());

  conf.setName(getName());
  conf.setAction(getAction());
  for (auto &i : getPortsList()) {
    conf.addPorts(i->toJsonObject());
  }

  return conf;
}
void MapwriterBase::addPortsList(const std::vector<PortsJsonObject> &conf) {
  for (auto &i : conf) {
    std::string name_ = i.getName();
    addPorts(name_, i);
  }
}

void MapwriterBase::replacePorts(const std::string &name, const PortsJsonObject &conf) {
  delPorts(name);
  std::string name_ = conf.getName();
  addPorts(name_, conf);
}

void MapwriterBase::delPortsList() {
  auto elements = getPortsList();
  for (auto &i : elements) {
    std::string name_ = i->getName();
    delPorts(name_);
  }
}

void MapwriterBase::addPorts(const std::string &name, const PortsJsonObject &conf) {
  add_port<PortsJsonObject>(name, conf);
}

void MapwriterBase::delPorts(const std::string &name) {
  remove_port(name);
}

std::shared_ptr<Ports> MapwriterBase::getPorts(const std::string &name) {
  return get_port(name);
}

std::vector<std::shared_ptr<Ports>> MapwriterBase::getPortsList() {
  return get_ports();
}


