/**
* ctxwriter API generated from ctxwriter.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */



#include "CtxwriterJsonObject.h"
#include <regex>

namespace polycube {
namespace service {
namespace model {

CtxwriterJsonObject::CtxwriterJsonObject() {
  m_nameIsSet = false;
  m_action = CtxwriterActionEnum::READ;
  m_actionIsSet = true;
  m_portsIsSet = false;
}

CtxwriterJsonObject::CtxwriterJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_nameIsSet = false;
  m_actionIsSet = false;
  m_portsIsSet = false;


  if (val.count("name")) {
    setName(val.at("name").get<std::string>());
  }

  if (val.count("action")) {
    setAction(string_to_CtxwriterActionEnum(val.at("action").get<std::string>()));
  }

  if (val.count("ports")) {
    for (auto& item : val["ports"]) {
      PortsJsonObject newItem{ item };
      m_ports.push_back(newItem);
    }

    m_portsIsSet = true;
  }
}

nlohmann::json CtxwriterJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_nameIsSet) {
    val["name"] = m_name;
  }

  if (m_actionIsSet) {
    val["action"] = CtxwriterActionEnum_to_string(m_action);
  }

  {
    nlohmann::json jsonArray;
    for (auto& item : m_ports) {
      jsonArray.push_back(JsonObjectBase::toJson(item));
    }

    if (jsonArray.size() > 0) {
      val["ports"] = jsonArray;
    }
  }

  return val;
}

std::string CtxwriterJsonObject::getName() const {
  return m_name;
}

void CtxwriterJsonObject::setName(std::string value) {
  m_name = value;
  m_nameIsSet = true;
}

bool CtxwriterJsonObject::nameIsSet() const {
  return m_nameIsSet;
}



CtxwriterActionEnum CtxwriterJsonObject::getAction() const {
  return m_action;
}

void CtxwriterJsonObject::setAction(CtxwriterActionEnum value) {
  m_action = value;
  m_actionIsSet = true;
}

bool CtxwriterJsonObject::actionIsSet() const {
  return m_actionIsSet;
}

void CtxwriterJsonObject::unsetAction() {
  m_actionIsSet = false;
}

std::string CtxwriterJsonObject::CtxwriterActionEnum_to_string(const CtxwriterActionEnum &value){
  switch(value) {
    case CtxwriterActionEnum::READ:
      return std::string("read");
    case CtxwriterActionEnum::WRITE:
      return std::string("write");
    default:
      throw std::runtime_error("Bad Ctxwriter action");
  }
}

CtxwriterActionEnum CtxwriterJsonObject::string_to_CtxwriterActionEnum(const std::string &str){
  if (JsonObjectBase::iequals("read", str))
    return CtxwriterActionEnum::READ;
  if (JsonObjectBase::iequals("write", str))
    return CtxwriterActionEnum::WRITE;
  throw std::runtime_error("Ctxwriter action is invalid");
}
const std::vector<PortsJsonObject>& CtxwriterJsonObject::getPorts() const{
  return m_ports;
}

void CtxwriterJsonObject::addPorts(PortsJsonObject value) {
  m_ports.push_back(value);
  m_portsIsSet = true;
}


bool CtxwriterJsonObject::portsIsSet() const {
  return m_portsIsSet;
}

void CtxwriterJsonObject::unsetPorts() {
  m_portsIsSet = false;
}


}
}
}

