/**
* ctxwriter API generated from ctxwriter.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* CtxwriterApi.h
*
*/

#pragma once

#define POLYCUBE_SERVICE_NAME "ctxwriter"


#include "polycube/services/response.h"
#include "polycube/services/shared_lib_elements.h"

#include "CtxwriterJsonObject.h"
#include "PortsJsonObject.h"
#include <vector>


#ifdef __cplusplus
extern "C" {
#endif

Response create_ctxwriter_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response create_ctxwriter_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response create_ctxwriter_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response delete_ctxwriter_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response delete_ctxwriter_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response delete_ctxwriter_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_ctxwriter_action_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_ctxwriter_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_ctxwriter_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_ctxwriter_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_ctxwriter_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response replace_ctxwriter_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response replace_ctxwriter_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response replace_ctxwriter_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_ctxwriter_action_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_ctxwriter_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_ctxwriter_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_ctxwriter_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_ctxwriter_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);

Response ctxwriter_list_by_id_help(const char *name, const Key *keys, size_t num_keys);
Response ctxwriter_ports_list_by_id_help(const char *name, const Key *keys, size_t num_keys);


#ifdef __cplusplus
}
#endif

