/**
* ctxwriter API generated from ctxwriter.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "CtxwriterApiImpl.h"

namespace polycube {
namespace service {
namespace api {

using namespace polycube::service::model;

namespace CtxwriterApiImpl {
namespace {
std::unordered_map<std::string, std::shared_ptr<Ctxwriter>> cubes;
std::mutex cubes_mutex;

std::shared_ptr<Ctxwriter> get_cube(const std::string &name) {
  std::lock_guard<std::mutex> guard(cubes_mutex);
  auto iter = cubes.find(name);
  if (iter == cubes.end()) {
    throw std::runtime_error("Cube " + name + " does not exist");
  }

  return iter->second;
}

}

void create_ctxwriter_by_id(const std::string &name, const CtxwriterJsonObject &jsonObject) {
  {
    // check if name is valid before creating it
    std::lock_guard<std::mutex> guard(cubes_mutex);
    if (cubes.count(name) != 0) {
      throw std::runtime_error("There is already a cube with name " + name);
    }
  }
  auto ptr = std::make_shared<Ctxwriter>(name, jsonObject);
  std::unordered_map<std::string, std::shared_ptr<Ctxwriter>>::iterator iter;
  bool inserted;

  std::lock_guard<std::mutex> guard(cubes_mutex);
  std::tie(iter, inserted) = cubes.emplace(name, std::move(ptr));

  if (!inserted) {
    throw std::runtime_error("There is already a cube with name " + name);
  }
}

void replace_ctxwriter_by_id(const std::string &name, const CtxwriterJsonObject &bridge){
  throw std::runtime_error("Method not supported!");
}

void delete_ctxwriter_by_id(const std::string &name) {
  std::lock_guard<std::mutex> guard(cubes_mutex);
  if (cubes.count(name) == 0) {
    throw std::runtime_error("Cube " + name + " does not exist");
  }
  cubes.erase(name);
}

std::vector<CtxwriterJsonObject> read_ctxwriter_list_by_id() {
  std::vector<CtxwriterJsonObject> jsonObject_vect;
  for(auto &i : cubes) {
    auto m = get_cube(i.first);
    jsonObject_vect.push_back(m->toJsonObject());
  }
  return jsonObject_vect;
}

std::vector<nlohmann::fifo_map<std::string, std::string>> read_ctxwriter_list_by_id_get_list() {
  std::vector<nlohmann::fifo_map<std::string, std::string>> r;
  for (auto &x : cubes) {
    nlohmann::fifo_map<std::string, std::string> m;
    m["name"] = x.first;
    r.push_back(std::move(m));
  }
  return r;
}

/**
* @brief   Create ports by ID
*
* Create operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] portsName ID of ports_name
* @param[in] value portsbody object
*
* Responses:
*
*/
void
create_ctxwriter_ports_by_id(const std::string &name, const std::string &portsName, const PortsJsonObject &value) {
  auto ctxwriter = get_cube(name);

  return ctxwriter->addPorts(portsName, value);
}

/**
* @brief   Create ports by ID
*
* Create operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] value portsbody object
*
* Responses:
*
*/
void
create_ctxwriter_ports_list_by_id(const std::string &name, const std::vector<PortsJsonObject> &value) {
  auto ctxwriter = get_cube(name);
  ctxwriter->addPortsList(value);
}

/**
* @brief   Delete ports by ID
*
* Delete operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] portsName ID of ports_name
*
* Responses:
*
*/
void
delete_ctxwriter_ports_by_id(const std::string &name, const std::string &portsName) {
  auto ctxwriter = get_cube(name);

  return ctxwriter->delPorts(portsName);
}

/**
* @brief   Delete ports by ID
*
* Delete operation of resource: ports*
*
* @param[in] name ID of name
*
* Responses:
*
*/
void
delete_ctxwriter_ports_list_by_id(const std::string &name) {
  auto ctxwriter = get_cube(name);
  ctxwriter->delPortsList();
}

/**
* @brief   Read action by ID
*
* Read operation of resource: action*
*
* @param[in] name ID of name
*
* Responses:
* CtxwriterActionEnum
*/
CtxwriterActionEnum
read_ctxwriter_action_by_id(const std::string &name) {
  auto ctxwriter = get_cube(name);
  return ctxwriter->getAction();

}

/**
* @brief   Read ctxwriter by ID
*
* Read operation of resource: ctxwriter*
*
* @param[in] name ID of name
*
* Responses:
* CtxwriterJsonObject
*/
CtxwriterJsonObject
read_ctxwriter_by_id(const std::string &name) {
  return get_cube(name)->toJsonObject();

}

/**
* @brief   Read ports by ID
*
* Read operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] portsName ID of ports_name
*
* Responses:
* PortsJsonObject
*/
PortsJsonObject
read_ctxwriter_ports_by_id(const std::string &name, const std::string &portsName) {
  auto ctxwriter = get_cube(name);
  return ctxwriter->getPorts(portsName)->toJsonObject();

}

/**
* @brief   Read ports by ID
*
* Read operation of resource: ports*
*
* @param[in] name ID of name
*
* Responses:
* std::vector<PortsJsonObject>
*/
std::vector<PortsJsonObject>
read_ctxwriter_ports_list_by_id(const std::string &name) {
  auto ctxwriter = get_cube(name);
  auto &&ports = ctxwriter->getPortsList();
  std::vector<PortsJsonObject> m;
  for(auto &i : ports)
    m.push_back(i->toJsonObject());
  return m;
}

/**
* @brief   Replace ports by ID
*
* Replace operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] portsName ID of ports_name
* @param[in] value portsbody object
*
* Responses:
*
*/
void
replace_ctxwriter_ports_by_id(const std::string &name, const std::string &portsName, const PortsJsonObject &value) {
  auto ctxwriter = get_cube(name);

  return ctxwriter->replacePorts(portsName, value);
}

/**
* @brief   Replace ports by ID
*
* Replace operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] value portsbody object
*
* Responses:
*
*/
void
replace_ctxwriter_ports_list_by_id(const std::string &name, const std::vector<PortsJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}

/**
* @brief   Update action by ID
*
* Update operation of resource: action*
*
* @param[in] name ID of name
* @param[in] value Action performed on the received packet (i.e.,READ, WRITE headers: READ)
*
* Responses:
*
*/
void
update_ctxwriter_action_by_id(const std::string &name, const CtxwriterActionEnum &value) {
  auto ctxwriter = get_cube(name);

  return ctxwriter->setAction(value);
}

/**
* @brief   Update ctxwriter by ID
*
* Update operation of resource: ctxwriter*
*
* @param[in] name ID of name
* @param[in] value ctxwriterbody object
*
* Responses:
*
*/
void
update_ctxwriter_by_id(const std::string &name, const CtxwriterJsonObject &value) {
  auto ctxwriter = get_cube(name);

  return ctxwriter->update(value);
}

/**
* @brief   Update ctxwriter by ID
*
* Update operation of resource: ctxwriter*
*
* @param[in] value ctxwriterbody object
*
* Responses:
*
*/
void
update_ctxwriter_list_by_id(const std::vector<CtxwriterJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}

/**
* @brief   Update ports by ID
*
* Update operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] portsName ID of ports_name
* @param[in] value portsbody object
*
* Responses:
*
*/
void
update_ctxwriter_ports_by_id(const std::string &name, const std::string &portsName, const PortsJsonObject &value) {
  auto ctxwriter = get_cube(name);
  auto ports = ctxwriter->getPorts(portsName);

  return ports->update(value);
}

/**
* @brief   Update ports by ID
*
* Update operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] value portsbody object
*
* Responses:
*
*/
void
update_ctxwriter_ports_list_by_id(const std::string &name, const std::vector<PortsJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}



/*
 * help related
 */

std::vector<nlohmann::fifo_map<std::string, std::string>> read_ctxwriter_ports_list_by_id_get_list(const std::string &name) {
  std::vector<nlohmann::fifo_map<std::string, std::string>> r;
  auto &&ctxwriter = get_cube(name);

  auto &&ports = ctxwriter->getPortsList();
  for(auto &i : ports) {
    nlohmann::fifo_map<std::string, std::string> keys;

    keys["name"] = i->getName();

    r.push_back(keys);
  }
  return r;
}


}

}
}
}

