/**
* ctxwriter API generated from ctxwriter.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "CtxwriterBase.h"

CtxwriterBase::CtxwriterBase(const std::string name) {
  logger()->set_pattern("[%Y-%m-%d %H:%M:%S.%e] [Ctxwriter] [%n] [%l] %v");
}



CtxwriterBase::~CtxwriterBase() {}

void CtxwriterBase::update(const CtxwriterJsonObject &conf) {
  set_conf(conf.getBase());

  if (conf.actionIsSet()) {
    setAction(conf.getAction());
  }
  if (conf.portsIsSet()) {
    for (auto &i : conf.getPorts()) {
      auto name = i.getName();
      auto m = getPorts(name);
      m->update(i);
    }
  }
}

CtxwriterJsonObject CtxwriterBase::toJsonObject() {
  CtxwriterJsonObject conf;
  conf.setBase(to_json());

  conf.setName(getName());
  conf.setAction(getAction());
  for (auto &i : getPortsList()) {
    conf.addPorts(i->toJsonObject());
  }

  return conf;
}
void CtxwriterBase::addPortsList(const std::vector<PortsJsonObject> &conf) {
  for (auto &i : conf) {
    std::string name_ = i.getName();
    addPorts(name_, i);
  }
}

void CtxwriterBase::replacePorts(const std::string &name, const PortsJsonObject &conf) {
  delPorts(name);
  std::string name_ = conf.getName();
  addPorts(name_, conf);
}

void CtxwriterBase::delPortsList() {
  auto elements = getPortsList();
  for (auto &i : elements) {
    std::string name_ = i->getName();
    delPorts(name_);
  }
}

void CtxwriterBase::addPorts(const std::string &name, const PortsJsonObject &conf) {
  add_port<PortsJsonObject>(name, conf);
}

void CtxwriterBase::delPorts(const std::string &name) {
  remove_port(name);
}

std::shared_ptr<Ports> CtxwriterBase::getPorts(const std::string &name) {
  return get_port(name);
}

std::vector<std::shared_ptr<Ports>> CtxwriterBase::getPortsList() {
  return get_ports();
}


