/**
* mapwriter API generated from mapwriter.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* MapwriterApi.h
*
*/

#pragma once

#define POLYCUBE_SERVICE_NAME "mapwriter"


#include "polycube/services/response.h"
#include "polycube/services/shared_lib_elements.h"

#include "MapwriterJsonObject.h"
#include "PortsJsonObject.h"
#include <vector>


#ifdef __cplusplus
extern "C" {
#endif

Response create_mapwriter_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response create_mapwriter_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response create_mapwriter_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response delete_mapwriter_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response delete_mapwriter_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response delete_mapwriter_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_mapwriter_action_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_mapwriter_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_mapwriter_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_mapwriter_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_mapwriter_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response replace_mapwriter_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response replace_mapwriter_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response replace_mapwriter_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_mapwriter_action_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_mapwriter_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_mapwriter_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_mapwriter_ports_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_mapwriter_ports_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);

Response mapwriter_list_by_id_help(const char *name, const Key *keys, size_t num_keys);
Response mapwriter_ports_list_by_id_help(const char *name, const Key *keys, size_t num_keys);


#ifdef __cplusplus
}
#endif

