/**
* mapwriter API generated from mapwriter.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* MapwriterJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"

#include "PortsJsonObject.h"
#include <vector>
#include "polycube/services/cube.h"

namespace polycube {
namespace service {
namespace model {

enum class MapwriterActionEnum {
  READ, WRITE
};

/// <summary>
///
/// </summary>
class  MapwriterJsonObject : public JsonObjectBase {
public:
  MapwriterJsonObject();
  MapwriterJsonObject(const nlohmann::json &json);
  ~MapwriterJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// Name of the mapwriter service
  /// </summary>
  std::string getName() const;
  void setName(std::string value);
  bool nameIsSet() const;

  /// <summary>
  /// Action performed on the received packet (i.e.,READ, WRITE headers: READ)
  /// </summary>
  MapwriterActionEnum getAction() const;
  void setAction(MapwriterActionEnum value);
  bool actionIsSet() const;
  void unsetAction();
  static std::string MapwriterActionEnum_to_string(const MapwriterActionEnum &value);
  static MapwriterActionEnum string_to_MapwriterActionEnum(const std::string &str);

  /// <summary>
  /// Entry of the ports table
  /// </summary>
  const std::vector<PortsJsonObject>& getPorts() const;
  void addPorts(PortsJsonObject value);
  bool portsIsSet() const;
  void unsetPorts();

private:
  std::string m_name;
  bool m_nameIsSet;
  MapwriterActionEnum m_action;
  bool m_actionIsSet;
  std::vector<PortsJsonObject> m_ports;
  bool m_portsIsSet;
};

}
}
}

